### PR TITLE
added teampage

### LINKED ISSUE #7: TeamPage
Create a page featuring team members

### PR DESCRIPTION
**Pull request by Mastersam07**
Screen for core team members and organizers

### CODE REVIEW

**Comment by Mastersam07** [comment]
fixes #7

**Review by gdg-ikorodu — CHANGES_REQUESTED** [review]
Kindly remove the static images and replace with real images. Also, fix the social actions. It does not seem to be working.

**Comment by Mastersam07** [comment]
Fixed the requested changes

**Review by gdg-ikorodu — APPROVED** [review]
okay for merging.

**Pull request merged**
